"""
Simulation Agent Tool Registry

Provides tool-use capabilities for simulation agents via OASIS's native
SocialAgent(tools=...) parameter. Handles:
- Universal tools (web search, news lookup)
- Scenario-specific tools generated by LLM from the simulation requirement
- Role-based tool assignment per agent
"""

import contextvars
import inspect
import json
import os
import re
import threading
from dataclasses import dataclass
from datetime import datetime
from typing import Any

from openai import OpenAI

from ..config import Config
from ..utils.logger import get_logger

logger = get_logger("glas.simulation_tools")

MAX_TOOL_OUTPUT_CHARS = 500


# ---------------------------------------------------------------------------
# Tool-call side-channel logger
# ---------------------------------------------------------------------------
# OASIS only records final social actions in its trace table. Tool calls
# happen inside CAMEL's agent loop and are invisible to the DB.  This logger
# captures every tool invocation so the action stream can include them.


class ToolCallLogger:
    """Thread-safe side-channel logger for tool invocations.

    Writes tool calls to a JSONL file and supports offset-based reads so each
    consumer (e.g. per-platform simulation loop) only sees new entries.
    """

    _instance_lock = threading.Lock()
    _instances: dict[str, "ToolCallLogger"] = {}

    def __init__(self, log_path: str):
        self._path = log_path
        self._lock = threading.Lock()
        self._readers: dict[str, int] = {}

    @classmethod
    def get_or_create(cls, simulation_dir: str) -> "ToolCallLogger":
        with cls._instance_lock:
            if simulation_dir not in cls._instances:
                path = os.path.join(simulation_dir, "tool_calls.jsonl")
                cls._instances[simulation_dir] = cls(path)
            return cls._instances[simulation_dir]

    @classmethod
    def set_active(cls, simulation_dir: str):
        """Set the active simulation dir so tool functions can find it."""
        cls._active_dir = simulation_dir

    @classmethod
    def get_active(cls) -> "ToolCallLogger | None":
        d = getattr(cls, "_active_dir", None)
        if d is None:
            return None
        return cls._instances.get(d)

    @classmethod
    def clear_instances(cls):
        """Clear cached instances (call between simulation runs)."""
        with cls._instance_lock:
            cls._instances.clear()
            cls._active_dir = None

    def log(self, agent_id: int, tool_name: str, args: dict, result: str, platform: str = ""):
        entry = {
            "timestamp": datetime.now().isoformat(),
            "agent_id": agent_id,
            "tool_name": tool_name,
            "tool_args": args,
            "tool_result": result[:MAX_TOOL_OUTPUT_CHARS],
            "platform": platform,
        }
        with self._lock, open(self._path, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    def fetch_new(self, reader_id: str = "default") -> list[dict]:
        """Return tool calls logged since this reader's last fetch.

        Each reader_id maintains its own offset, so Twitter and Reddit
        simulation loops can independently consume the same log file
        without stealing each other's entries.
        """
        entries = []
        with self._lock:
            if not os.path.exists(self._path):
                return entries
            offset = self._readers.get(reader_id, 0)
            with open(self._path, encoding="utf-8") as f:
                f.seek(offset)
                for line in f:
                    line = line.strip()
                    if line:
                        try:
                            entries.append(json.loads(line))
                        except json.JSONDecodeError:
                            pass
                self._readers[reader_id] = f.tell()
        return entries


# Tracks which agent/platform is currently executing a tool call (set by per-agent wrappers)
_current_agent_id: contextvars.ContextVar[int] = contextvars.ContextVar("_current_agent_id", default=-1)
_current_platform: contextvars.ContextVar[str] = contextvars.ContextVar("_current_platform", default="")


# ---------------------------------------------------------------------------
# Universal tool functions
# ---------------------------------------------------------------------------


def _log_tool_call(tool_name: str, args: dict, result: str):
    """Log a tool invocation to the side-channel if a logger is active."""
    tcl = ToolCallLogger.get_active()
    if tcl is not None:
        tcl.log(
            agent_id=_current_agent_id.get(),
            tool_name=tool_name,
            args=args,
            result=result,
            platform=_current_platform.get(),
        )


_search_toolkit_cache = None


def _ddg_search(query: str, max_results: int = 3) -> str:
    """Run a DuckDuckGo text search, trying CAMEL toolkit first, then direct."""
    global _search_toolkit_cache
    try:
        if _search_toolkit_cache is None:
            from camel.toolkits import SearchToolkit

            _search_toolkit_cache = SearchToolkit()
        raw = _search_toolkit_cache.search_duckduckgo(query=query, max_results=max_results)
        return str(raw)[:MAX_TOOL_OUTPUT_CHARS] if raw else ""
    except Exception:
        pass
    try:
        from duckduckgo_search import DDGS

        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=max_results))
        if results:
            lines = [f"- {r.get('title', '')}: {r.get('body', '')}" for r in results]
            return "\n".join(lines)[:MAX_TOOL_OUTPUT_CHARS]
    except Exception:
        pass
    return ""


def web_search(query: str) -> str:
    """Search the web using DuckDuckGo and return a concise summary of results.

    Use this tool when you need current facts, news, or data to inform your
    social media posts or decisions.

    Args:
        query (str): The search query string.

    Returns:
        str: A summary of the top search results (max 500 chars).
    """
    try:
        result = _ddg_search(query) or "No results found."
        _log_tool_call("web_search", {"query": query}, result)
        return result
    except Exception as e:
        logger.warning(f"web_search failed for '{query}': {e}")
        return f"Search unavailable: {e}"


def lookup_news(topic: str) -> str:
    """Look up recent news articles about a topic using DuckDuckGo news search.

    Use this tool when you need the latest news coverage on a specific topic
    to reference or react to in your posts.

    Args:
        topic (str): The news topic to search for.

    Returns:
        str: A summary of recent news articles (max 500 chars).
    """
    try:
        result = _ddg_search(f"{topic} latest news") or "No news found."
        _log_tool_call("lookup_news", {"topic": topic}, result)
        return result
    except Exception as e:
        logger.warning(f"lookup_news failed for '{topic}': {e}")
        return f"News lookup unavailable: {e}"


def lookup_financial_data(query: str) -> str:
    """Look up financial or economic data related to a query.

    Use this tool when you need market data, economic indicators, or
    financial information to inform your analysis or posts.

    Args:
        query (str): The financial topic or instrument to look up (e.g.
            'oil prices', 'US GDP growth', 'AAPL stock').

    Returns:
        str: A summary of relevant financial data (max 500 chars).
    """
    try:
        result = _ddg_search(f"{query} financial data market") or "No financial data found."
        _log_tool_call("lookup_financial_data", {"query": query}, result)
        return result
    except Exception as e:
        logger.warning(f"lookup_financial_data failed for '{query}': {e}")
        return f"Financial data unavailable: {e}"


# ---------------------------------------------------------------------------
# Scenario-specific tool generation
# ---------------------------------------------------------------------------

_SCENARIO_TOOL_PROMPT = """\
You are designing tools for AI agents in a social media simulation.

The simulation scenario is:
{simulation_requirement}

The agents represent these entity types: {entity_types}

Generate 3-5 scenario-specific action tools that agents could use beyond
social media posting. Each tool should:
- Be a meaningful action within the scenario (e.g. propose_sanction,
  form_alliance, issue_statement, deploy_resources, call_vote)
- Accept string arguments that describe the action
- Return a string description of what happened (this becomes visible on
  the social feed)
- Produce mechanical side effects on the simulation state

Return a JSON array of tool definitions. Each definition has:
- "name": snake_case function name (max 30 chars)
- "description": What the tool does and when to use it (2-3 sentences)
- "param_name": Name of the main string parameter
- "param_description": Description of what to pass
- "effects": Array of state effects this tool produces. Each effect has:
  - "effect_type": one of "suppress_agent", "boost_agent", "create_link", "break_link", "broadcast"
  - "target": "self" (affects the calling agent), "named" (target extracted from action_description), or "all"
  - "magnitude": 0.0-0.7 (how strong the effect is, e.g. 0.2=mild, 0.5=significant, 0.7=severe)
  - "direction": "actor_to_target" or "target_to_actor" or "bidirectional" (for link effects only)

Effect types explained:
- suppress_agent: Reduces target's activity_level (they post less frequently)
- boost_agent: Increases target's activity_level (they post more frequently)
- create_link: Creates a follow relationship between agents (they see each other's content)
- break_link: Removes a follow relationship (they stop seeing each other's content)
- broadcast: No state change, just a visible announcement in the feed

Example:
[
  {{
    "name": "propose_sanction",
    "description": "Propose economic sanctions against a nation or entity. Use when you want to take a formal economic action against another party.",
    "param_name": "proposal",
    "param_description": "Description of the sanctions: target, severity (limited/moderate/severe), and rationale",
    "effects": [
      {{"effect_type": "suppress_agent", "target": "named", "magnitude": 0.4}},
      {{"effect_type": "break_link", "target": "named", "direction": "bidirectional"}}
    ]
  }},
  {{
    "name": "form_alliance",
    "description": "Form a strategic alliance with another entity. Use when you want to strengthen ties and increase cooperation.",
    "param_name": "alliance_details",
    "param_description": "Description of the alliance: partner, terms, and strategic objectives",
    "effects": [
      {{"effect_type": "create_link", "target": "named", "direction": "bidirectional"}},
      {{"effect_type": "boost_agent", "target": "named", "magnitude": 0.2}}
    ]
  }}
]

Return ONLY the JSON array, no other text."""


@dataclass
class ScenarioToolDef:
    """Definition of a scenario-specific tool generated by LLM."""

    name: str
    description: str
    param_name: str
    param_description: str
    effects: list[dict] = None  # List of effect specs from LLM

    def __post_init__(self):
        if self.effects is None:
            self.effects = []


def generate_scenario_tool_definitions(
    simulation_requirement: str,
    entity_types: list[str],
) -> list[ScenarioToolDef]:
    """Use LLM to generate scenario-specific tool definitions."""
    if not Config.LLM_API_KEY:
        logger.warning("No LLM_API_KEY — skipping scenario tool generation")
        return []

    entity_str = ", ".join(entity_types[:10]) if entity_types else "various stakeholders"
    prompt = _SCENARIO_TOOL_PROMPT.format(
        simulation_requirement=simulation_requirement,
        entity_types=entity_str,
    )

    try:
        client = OpenAI(api_key=Config.LLM_API_KEY, base_url=Config.LLM_BASE_URL)
        response = client.chat.completions.create(
            model=Config.LLM_MODEL_NAME,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=2500,
        )
        raw = response.choices[0].message.content.strip()

        json_match = re.search(r"\[.*\]", raw, re.DOTALL)
        if not json_match:
            logger.warning("LLM did not return valid JSON array for scenario tools")
            return []

        definitions = json.loads(json_match.group())
        valid_effect_types = {"suppress_agent", "boost_agent", "create_link", "break_link", "broadcast"}
        tools = []
        for d in definitions[:5]:
            name = re.sub(r"[^a-z0-9_]", "", d.get("name", "")[:30])
            if not name:
                continue
            raw_effects = d.get("effects", [])
            effects = []
            for eff in raw_effects or []:
                if eff.get("effect_type") in valid_effect_types:
                    effects.append(
                        {
                            "effect_type": eff["effect_type"],
                            "target": eff.get("target", "named"),
                            "magnitude": min(float(eff.get("magnitude", 0.4)), 0.7),
                            "direction": eff.get("direction", "actor_to_target"),
                        }
                    )
            tools.append(
                ScenarioToolDef(
                    name=name,
                    description=d.get("description", "Perform a scenario action."),
                    param_name=d.get("param_name", "action_description"),
                    param_description=d.get("param_description", "Description of the action to take"),
                    effects=effects,
                )
            )
        logger.info(f"Generated {len(tools)} scenario tools: {[t.name for t in tools]}")
        return tools

    except Exception as e:
        logger.error(f"Failed to generate scenario tools: {e}")
        return []


_effect_engine_ref = None


def set_effect_engine(engine):
    """Set the global effect engine reference for tool functions to queue effects."""
    global _effect_engine_ref
    _effect_engine_ref = engine


def _make_scenario_tool_function(tool_def: ScenarioToolDef):
    """Create a callable function from a ScenarioToolDef.

    Dynamically builds a function with proper signature, docstring, and
    type annotations so CAMEL's FunctionTool can introspect it.
    When the tool has effects, queues StateEffect instances on the global
    EffectEngine.
    """
    from .simulation_effects import EffectType, StateEffect

    effects_specs = tool_def.effects or []

    def tool_fn(action_description: str) -> str:
        result = f"[{tool_def.name.upper()}] {action_description}"
        _log_tool_call(tool_def.name, {"action_description": action_description}, result)

        engine = _effect_engine_ref
        if engine and effects_specs:
            actor_id = _current_agent_id.get()
            platform = _current_platform.get()
            for spec in effects_specs:
                target_name = ""
                target_id = None

                if spec.get("target") == "self":
                    target_id = actor_id
                elif spec.get("target") == "named":
                    target_name = action_description
                # "all" leaves target_id None, handled by BROADCAST

                try:
                    etype = EffectType(spec["effect_type"])
                except ValueError:
                    continue

                engine.queue(
                    StateEffect(
                        effect_type=etype,
                        actor_id=actor_id,
                        target_id=target_id,
                        target_name=target_name,
                        magnitude=spec.get("magnitude", 0.4),
                        direction=spec.get("direction", "actor_to_target"),
                        tool_name=tool_def.name,
                        tool_args={"action_description": action_description},
                        platform=platform,
                    )
                )

        return result

    tool_fn.__name__ = tool_def.name
    tool_fn.__qualname__ = tool_def.name
    tool_fn.__doc__ = (
        f"{tool_def.description}\n\n"
        f"Args:\n"
        f"    action_description (str): {tool_def.param_description}\n\n"
        f"Returns:\n"
        f"    str: A description of the action taken."
    )
    tool_fn.__annotations__ = {"action_description": str, "return": str}
    return tool_fn


# ---------------------------------------------------------------------------
# Role-based tool assignment
# ---------------------------------------------------------------------------

_ROLE_TOOL_PROMPT = """\
You are assigning tool roles to agents in a social media simulation.

Simulation scenario: {simulation_requirement}

Available tool roles:
- "leader": Government officials, heads of state, corporate executives. Gets: scenario action tools + web search
- "diplomat": Diplomats, negotiators, mediators. Gets: scenario action tools + web search + news
- "analyst": Researchers, journalists, think tank members. Gets: web search + news + financial data
- "operative": Military, intelligence, field operatives. Gets: scenario action tools + web search
- "observer": Citizens, activists, commentators. Gets: web search only
- "none": Agents that should NOT have tools (purely social media participants)

For each agent below, assign exactly one role. Consider their entity type,
name, and stance.

Agents:
{agent_list}

Return a JSON object mapping agent_id (as string) to role.
Example: {{"0": "leader", "1": "analyst", "2": "observer"}}

Return ONLY the JSON object, no other text."""


def assign_tool_roles(
    agent_configs: list[dict[str, Any]],
    simulation_requirement: str,
) -> dict[int, str]:
    """Use LLM to assign tool roles to agents based on their entity type and stance."""
    if not Config.LLM_API_KEY or not agent_configs:
        return {}

    agent_lines = []
    for ac in agent_configs:
        agent_lines.append(
            f"- Agent {ac.get('agent_id', '?')}: "
            f"name={ac.get('entity_name', 'unknown')}, "
            f"type={ac.get('entity_type', 'unknown')}, "
            f"stance={ac.get('stance', 'neutral')}"
        )
    agent_list_str = "\n".join(agent_lines)

    prompt = _ROLE_TOOL_PROMPT.format(
        simulation_requirement=simulation_requirement,
        agent_list=agent_list_str,
    )

    try:
        client = OpenAI(api_key=Config.LLM_API_KEY, base_url=Config.LLM_BASE_URL)
        response = client.chat.completions.create(
            model=Config.LLM_MODEL_NAME,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=1000,
        )
        raw = response.choices[0].message.content.strip()

        json_match = re.search(r"\{.*\}", raw, re.DOTALL)
        if not json_match:
            logger.warning("LLM did not return valid JSON for tool role assignments")
            return {}

        role_map = json.loads(json_match.group())
        result = {}
        valid_roles = {"leader", "diplomat", "analyst", "operative", "observer", "none"}
        for agent_id_str, role in role_map.items():
            try:
                aid = int(agent_id_str)
                result[aid] = role if role in valid_roles else "observer"
            except ValueError:
                continue

        logger.info(f"Assigned tool roles: {result}")
        return result

    except Exception as e:
        logger.error(f"Failed to assign tool roles: {e}")
        return {}


# ---------------------------------------------------------------------------
# Tool Registry — assembles everything
# ---------------------------------------------------------------------------


class ToolRegistry:
    """Assembles and caches tools for a simulation run.

    Usage:
        registry = ToolRegistry(config, simulation_requirement)
        tools_for_agent = registry.get_tools_for_agent(agent_id)
    """

    def __init__(
        self,
        simulation_config: dict[str, Any],
        simulation_requirement: str = "",
        enable_tools: bool = True,
    ):
        self._config = simulation_config
        self._requirement = simulation_requirement
        self._enabled = enable_tools
        self._scenario_tools: list[ScenarioToolDef] = []
        self._scenario_fns: list = []
        self._role_map: dict[int, str] = {}
        self._built = False

    def build(self, progress_callback=None):
        """Generate scenario tools and assign roles. Call once before simulation starts.

        If agent_configs already contain a 'tool_role' field (set by the
        config generator), those roles are reused instead of making a
        second LLM call.
        """
        if not self._enabled or self._built:
            return

        agent_configs = self._config.get("agent_configs", [])
        entity_types = list({ac.get("entity_type", "") for ac in agent_configs if ac.get("entity_type")})

        if progress_callback:
            progress_callback("Generating scenario-specific tools...")

        self._scenario_tools = generate_scenario_tool_definitions(self._requirement, entity_types)
        self._scenario_fns = [_make_scenario_tool_function(td) for td in self._scenario_tools]

        if progress_callback:
            progress_callback("Assigning tool roles to agents...")

        pre_assigned = {
            ac["agent_id"]: ac["tool_role"] for ac in agent_configs if ac.get("tool_role") and ac["tool_role"] != "none"
        }
        if pre_assigned:
            self._role_map = pre_assigned
            logger.info(f"Reusing {len(pre_assigned)} pre-assigned tool roles from config")
        else:
            self._role_map = assign_tool_roles(agent_configs, self._requirement)

        self._built = True
        logger.info(
            f"ToolRegistry built: {len(self._scenario_tools)} scenario tools, {len(self._role_map)} role assignments"
        )

    @property
    def scenario_tool_names(self) -> list[str]:
        return [t.name for t in self._scenario_tools]

    @property
    def role_map(self) -> dict[int, str]:
        return dict(self._role_map)

    @staticmethod
    def _bind_context(fn, agent_id: int, platform: str = ""):
        """Wrap a tool function so _current_agent_id and _current_platform
        are set when it executes.

        Preserves __name__, __doc__, __annotations__, and critically
        __signature__ so CAMEL's FunctionTool can introspect the wrapper
        exactly as it would the original function.
        """

        def wrapper(*args, **kwargs):
            id_token = _current_agent_id.set(agent_id)
            plat_token = _current_platform.set(platform)
            try:
                return fn(*args, **kwargs)
            finally:
                _current_platform.reset(plat_token)
                _current_agent_id.reset(id_token)

        wrapper.__name__ = fn.__name__
        wrapper.__qualname__ = fn.__qualname__
        wrapper.__doc__ = fn.__doc__
        wrapper.__module__ = getattr(fn, "__module__", __name__)
        wrapper.__annotations__ = getattr(fn, "__annotations__", {})
        wrapper.__signature__ = inspect.signature(fn)
        return wrapper

    def get_tools_for_agent(self, agent_id: int, platform: str = "") -> list | None:
        """Return list of FunctionTool instances for an agent, or None if no tools."""
        if not self._enabled or not self._built:
            return None

        role = self._role_map.get(agent_id, "none")
        if role == "none":
            return None

        try:
            from camel.toolkits import FunctionTool
        except ImportError:
            logger.error("camel.toolkits not available — cannot assign tools")
            return None

        def bind(fn):
            return self._bind_context(fn, agent_id, platform)

        tools = []

        if role == "leader":
            tools.append(FunctionTool(bind(web_search)))
            tools.extend(FunctionTool(bind(fn)) for fn in self._scenario_fns)
        elif role == "diplomat":
            tools.append(FunctionTool(bind(web_search)))
            tools.append(FunctionTool(bind(lookup_news)))
            tools.extend(FunctionTool(bind(fn)) for fn in self._scenario_fns)
        elif role == "analyst":
            tools.append(FunctionTool(bind(web_search)))
            tools.append(FunctionTool(bind(lookup_news)))
            tools.append(FunctionTool(bind(lookup_financial_data)))
        elif role == "operative":
            tools.append(FunctionTool(bind(web_search)))
            tools.extend(FunctionTool(bind(fn)) for fn in self._scenario_fns)
        elif role == "observer":
            tools.append(FunctionTool(bind(web_search)))

        return tools if tools else None

    def get_max_iterations(self, agent_id: int) -> int:
        """Return max LLM iterations per step for an agent (controls tool call depth)."""
        role = self._role_map.get(agent_id, "none")
        if role in ("leader", "diplomat"):
            return 3
        if role in ("analyst", "operative"):
            return 2
        return 1

    def to_dict(self) -> dict[str, Any]:
        """Serialize registry state for logging/config storage."""
        return {
            "enabled": self._enabled,
            "scenario_tools": [
                {"name": t.name, "description": t.description, "effects": t.effects} for t in self._scenario_tools
            ],
            "role_assignments": {str(k): v for k, v in self._role_map.items()},
        }
