const { chromium } = require('@playwright/test')
;(async () => {
  const browser = await chromium.launch()
  const page = await browser.newPage()
  page.on('console', m => console.log('[console]', m.type(), m.text().slice(0, 150)))
  page.on('requestfailed', r => console.log('[reqfail]', r.url().slice(0, 100), r.failure()?.errorText))
  await page.goto('http://localhost:3000/', { timeout: 15000 })
  await page.waitForTimeout(5000)
  console.log('URL:', page.url())
  console.log('demo banner:', await page.getByText('Demo — replaying a recorded simulation').count())
  console.log('scenario cards:', await page.locator('[data-test="scenario-card"]').count())
  const body = await page.locator('body').innerText()
  console.log('BODY SNIPPET:', body.slice(0, 300).replace(/\n/g, ' | '))
  await browser.close()
})().catch(e => { console.error('PROBE FAIL:', e.message); process.exit(1) })
