"""
Simulation API routes
Step 2: Zep entity reading & filtering, OASIS simulation preparation & execution (fully automated)
"""

import json
import os
import traceback
from flask import request, jsonify, send_file, g

from . import simulation_bp
from ..config import Config
from ..middleware.auth import require_auth
from ..services.zep_entity_reader import ZepEntityReader
from ..services.oasis_profile_generator import OasisProfileGenerator
from ..services.simulation_manager import SimulationManager, SimulationStatus
from ..services.simulation_runner import SimulationRunner
from ..services.report_agent import ReportManager
from ..utils.logger import get_logger
from ..models.project import ProjectManager
from ..services.supabase_client import SupabaseDB

logger = get_logger("glas.api.simulation")

from . import simulation_entities  # noqa: F401  # registers entity routes on simulation_bp
from .simulation_helpers import check_simulation_prepared

# ============== Simulation Management Endpoints ==============


@simulation_bp.route("/create", methods=["POST"])
@require_auth
def create_simulation():
    """
    Create a new simulation

    Note: max_rounds and other parameters are intelligently generated by LLM, no manual setup needed

    Request (JSON):
        {
            "project_id": "proj_xxxx",      // required
            "graph_id": "glas_xxxx",    // optional, if not provided will be fetched from project
            "enable_twitter": true,          // optional, default true
            "enable_reddit": true            // optional, default true
        }

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "project_id": "proj_xxxx",
                "graph_id": "glas_xxxx",
                "status": "created",
                "enable_twitter": true,
                "enable_reddit": true,
                "created_at": "2025-12-01T10:00:00"
            }
        }
    """
    try:
        data = request.get_json() or {}

        project_id = data.get("project_id")
        if not project_id:
            return jsonify({"success": False, "error": "Please provide project_id"}), 400

        project = ProjectManager.get_project(project_id)
        if not project:
            return jsonify({"success": False, "error": f"Project not found: {project_id}"}), 404

        graph_id = data.get("graph_id") or project.graph_id
        if not graph_id:
            return jsonify(
                {"success": False, "error": "Graph not yet built for project, please call /api/graph/build first"}
            ), 400

        manager = SimulationManager()
        state = manager.create_simulation(
            project_id=project_id,
            graph_id=graph_id,
            enable_twitter=data.get("enable_twitter", True),
            enable_reddit=data.get("enable_reddit", True),
        )

        session_id = data.get("session_id")
        if session_id and isinstance(session_id, str):
            sess = SupabaseDB.get_session(session_id, user_id=g.user_id)
            if sess:
                SupabaseDB.update_session(
                    session_id,
                    graph_id=graph_id,
                    project_id=project_id,
                )
                SupabaseDB.propagate_graph_id_for_project(project_id, graph_id)

        return jsonify({"success": True, "data": state.to_dict()})

    except Exception as e:
        logger.error(f"Failed to create simulation: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


@simulation_bp.route("/prepare", methods=["POST"])
@require_auth
def prepare_simulation():
    """
    Prepare simulation environment (async task, LLM intelligently generates all parameters)

    This is a long-running operation. The endpoint returns a task_id immediately.
    Use POST /api/simulation/prepare/status to query progress.

    Features:
    - Auto-detects completed preparation work to avoid regeneration
    - If already prepared, returns existing results directly
    - Supports forced regeneration (force_regenerate=true)

    Steps:
    1. Check if preparation is already complete
    2. Read and filter entities from Zep graph
    3. Generate OASIS Agent Profile for each entity (with retry mechanism)
    4. LLM intelligently generates simulation config (with retry mechanism)
    5. Save config files and preset scripts

    Request (JSON):
        {
            "simulation_id": "sim_xxxx",                   // required
            "entity_types": ["Student", "PublicFigure"],  // optional, specify entity types
            "use_llm_for_profiles": true,                 // optional, use LLM for profile generation
            "parallel_profile_count": 5,                  // optional, parallel profile generation count, default 5
            "force_regenerate": false                     // optional, force regeneration, default false
        }

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "task_id": "task_xxxx",           // returned for new tasks
                "status": "preparing|ready",
                "message": "Preparation task started|Already prepared",
                "already_prepared": true|false
            }
        }
    """
    import threading
    from ..models.task import TaskManager, TaskStatus

    try:
        data = request.get_json() or {}

        simulation_id = data.get("simulation_id")
        if not simulation_id:
            return jsonify({"success": False, "error": "Please provide simulation_id"}), 400

        manager = SimulationManager()
        state = manager.get_simulation(simulation_id)

        if not state:
            return jsonify({"success": False, "error": f"Simulation not found: {simulation_id}"}), 404

        force_regenerate = data.get("force_regenerate", False)
        logger.info(f"Processing /prepare request: simulation_id={simulation_id}, force_regenerate={force_regenerate}")

        if not force_regenerate:
            logger.debug(f"Checking if simulation {simulation_id} is already prepared...")
            is_prepared, prepare_info = check_simulation_prepared(simulation_id)
            logger.debug(f"Check result: is_prepared={is_prepared}, prepare_info={prepare_info}")
            if is_prepared:
                logger.info(f"Simulation {simulation_id} already prepared, skipping regeneration")
                return jsonify(
                    {
                        "success": True,
                        "data": {
                            "simulation_id": simulation_id,
                            "status": "ready",
                            "message": "Preparation already complete, no regeneration needed",
                            "already_prepared": True,
                            "prepare_info": prepare_info,
                        },
                    }
                )
            else:
                logger.info(f"Simulation {simulation_id} not prepared, starting preparation task")

        project = ProjectManager.get_project(state.project_id)
        if not project:
            return jsonify({"success": False, "error": f"Project not found: {state.project_id}"}), 404

        simulation_requirement = project.simulation_requirement or ""
        if not simulation_requirement:
            return jsonify(
                {
                    "success": False,
                    "error": "Project missing simulation requirement description (simulation_requirement)",
                }
            ), 400

        document_text = ProjectManager.get_extracted_text(state.project_id) or ""

        profile = SupabaseDB.get_profile(g.user_id)
        user_plan = Config.normalize_plan(profile.get("plan", "free") if profile else "free")

        entity_types_list = data.get("entity_types")
        use_llm_for_profiles = data.get("use_llm_for_profiles", True)
        parallel_profile_count = data.get("parallel_profile_count", 5)

        try:
            logger.info(f"Synchronously fetching entity count: graph_id={state.graph_id}")
            reader = ZepEntityReader()
            filtered_preview = reader.filter_defined_entities(
                graph_id=state.graph_id, defined_entity_types=entity_types_list, enrich_with_edges=False
            )
            state.entities_count = filtered_preview.filtered_count
            state.entity_types = list(filtered_preview.entity_types)
            logger.info(
                f"Expected entity count: {filtered_preview.filtered_count}, types: {filtered_preview.entity_types}"
            )
        except Exception as e:
            logger.warning(f"Synchronous entity count fetch failed (will retry in background task): {e}")

        task_manager = TaskManager()
        task_id = task_manager.create_task(
            task_type="simulation_prepare", metadata={"simulation_id": simulation_id, "project_id": state.project_id}
        )

        state.status = SimulationStatus.PREPARING
        manager._save_simulation_state(state)

        def run_prepare():
            try:
                task_manager.update_task(
                    task_id,
                    status=TaskStatus.PROCESSING,
                    progress=0,
                    message="Starting simulation environment preparation...",
                )

                stage_details = {}

                def progress_callback(stage, progress, message, **kwargs):
                    stage_weights = {
                        "reading": (0, 20),
                        "generating_profiles": (20, 70),
                        "generating_config": (70, 90),
                        "copying_scripts": (90, 100),
                    }

                    start, end = stage_weights.get(stage, (0, 100))
                    current_progress = int(start + (end - start) * progress / 100)

                    stage_names = {
                        "reading": "Reading graph entities",
                        "generating_profiles": "Generating Agent profiles",
                        "generating_config": "Generating simulation config",
                        "copying_scripts": "Preparing simulation scripts",
                    }

                    stage_index = list(stage_weights.keys()).index(stage) + 1 if stage in stage_weights else 1
                    total_stages = len(stage_weights)

                    stage_details[stage] = {
                        "stage_name": stage_names.get(stage, stage),
                        "stage_progress": progress,
                        "current": kwargs.get("current", 0),
                        "total": kwargs.get("total", 0),
                        "item_name": kwargs.get("item_name", ""),
                    }

                    detail = stage_details[stage]
                    progress_detail_data = {
                        "current_stage": stage,
                        "current_stage_name": stage_names.get(stage, stage),
                        "stage_index": stage_index,
                        "total_stages": total_stages,
                        "stage_progress": progress,
                        "current_item": detail["current"],
                        "total_items": detail["total"],
                        "item_description": message,
                    }

                    if detail["total"] > 0:
                        detailed_message = (
                            f"[{stage_index}/{total_stages}] {stage_names.get(stage, stage)}: "
                            f"{detail['current']}/{detail['total']} - {message}"
                        )
                    else:
                        detailed_message = f"[{stage_index}/{total_stages}] {stage_names.get(stage, stage)}: {message}"

                    task_manager.update_task(
                        task_id,
                        progress=current_progress,
                        message=detailed_message,
                        progress_detail=progress_detail_data,
                    )

                result_state = manager.prepare_simulation(
                    simulation_id=simulation_id,
                    simulation_requirement=simulation_requirement,
                    document_text=document_text,
                    defined_entity_types=entity_types_list,
                    use_llm_for_profiles=use_llm_for_profiles,
                    progress_callback=progress_callback,
                    parallel_profile_count=parallel_profile_count,
                    user_plan=user_plan,
                )

                task_manager.complete_task(task_id, result=result_state.to_simple_dict())

            except Exception as e:
                logger.error(f"Simulation preparation failed: {str(e)}")
                task_manager.fail_task(task_id, str(e))

                state = manager.get_simulation(simulation_id)
                if state:
                    state.status = SimulationStatus.FAILED
                    state.error = str(e)
                    manager._save_simulation_state(state)

        thread = threading.Thread(target=run_prepare, daemon=True)
        thread.start()

        return jsonify(
            {
                "success": True,
                "data": {
                    "simulation_id": simulation_id,
                    "task_id": task_id,
                    "status": "preparing",
                    "message": "Preparation task started, query progress via /api/simulation/prepare/status",
                    "already_prepared": False,
                    "expected_entities_count": state.entities_count,
                    "entity_types": state.entity_types,
                },
            }
        )

    except ValueError as e:
        return jsonify({"success": False, "error": str(e)}), 404

    except Exception as e:
        logger.error(f"Failed to start preparation task: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


@simulation_bp.route("/prepare/status", methods=["POST"])
@require_auth
def get_prepare_status():
    """
    Query preparation task progress

    Supports two query methods:
    1. Query in-progress task via task_id
    2. Check completed preparation via simulation_id

    Request (JSON):
        {
            "task_id": "task_xxxx",          // optional, task_id from prepare
            "simulation_id": "sim_xxxx"      // optional, simulation ID (to check completed preparation)
        }

    Returns:
        {
            "success": true,
            "data": {
                "task_id": "task_xxxx",
                "status": "processing|completed|ready",
                "progress": 45,
                "message": "...",
                "already_prepared": true|false,
                "prepare_info": {...}
            }
        }
    """
    from ..models.task import TaskManager

    try:
        data = request.get_json() or {}

        task_id = data.get("task_id")
        simulation_id = data.get("simulation_id")

        if simulation_id:
            is_prepared, prepare_info = check_simulation_prepared(simulation_id)
            if is_prepared:
                return jsonify(
                    {
                        "success": True,
                        "data": {
                            "simulation_id": simulation_id,
                            "status": "ready",
                            "progress": 100,
                            "message": "Preparation already complete",
                            "already_prepared": True,
                            "prepare_info": prepare_info,
                        },
                    }
                )

        if not task_id:
            if simulation_id:
                return jsonify(
                    {
                        "success": True,
                        "data": {
                            "simulation_id": simulation_id,
                            "status": "not_started",
                            "progress": 0,
                            "message": "Preparation not started, please call /api/simulation/prepare to begin",
                            "already_prepared": False,
                        },
                    }
                )
            return jsonify({"success": False, "error": "Please provide task_id or simulation_id"}), 400

        task_manager = TaskManager()
        task = task_manager.get_task(task_id)

        if not task:
            if simulation_id:
                is_prepared, prepare_info = check_simulation_prepared(simulation_id)
                if is_prepared:
                    return jsonify(
                        {
                            "success": True,
                            "data": {
                                "simulation_id": simulation_id,
                                "task_id": task_id,
                                "status": "ready",
                                "progress": 100,
                                "message": "Task completed (preparation already exists)",
                                "already_prepared": True,
                                "prepare_info": prepare_info,
                            },
                        }
                    )

            return jsonify({"success": False, "error": f"Task not found: {task_id}"}), 404

        task_dict = task.to_dict()
        task_dict["already_prepared"] = False

        return jsonify({"success": True, "data": task_dict})

    except Exception as e:
        logger.error(f"Failed to query task status: {str(e)}")
        return jsonify({"success": False, "error": str(e)}), 500


@simulation_bp.route("/<simulation_id>", methods=["GET"])
@require_auth
def get_simulation(simulation_id: str):
    """Get simulation status"""
    try:
        manager = SimulationManager()
        state = manager.get_simulation(simulation_id)

        if not state:
            return jsonify({"success": False, "error": f"Simulation not found: {simulation_id}"}), 404

        result = state.to_dict()

        if state.status == SimulationStatus.READY:
            result["run_instructions"] = manager.get_run_instructions(simulation_id)

        return jsonify({"success": True, "data": result})

    except Exception as e:
        logger.error(f"Failed to get simulation status: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


@simulation_bp.route("/list", methods=["GET"])
@require_auth
def list_simulations():
    """
    List all simulations

    Query parameters:
        project_id: Filter by project ID (optional)
    """
    try:
        project_id = request.args.get("project_id")

        manager = SimulationManager()
        simulations = manager.list_simulations(project_id=project_id)

        return jsonify({"success": True, "data": [s.to_dict() for s in simulations], "count": len(simulations)})

    except Exception as e:
        logger.error(f"Failed to list simulations: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


def _get_report_id_for_simulation(simulation_id: str) -> str:
    """
    Get the latest report_id for a simulation.

    Scans the reports directory for matching simulation_id,
    returns the most recent one (sorted by created_at).

    Args:
        simulation_id: Simulation ID

    Returns:
        report_id or None
    """

    reports_dir = os.path.join(os.path.dirname(__file__), "../../uploads/reports")
    if not os.path.exists(reports_dir):
        return None

    matching_reports = []

    try:
        for report_folder in os.listdir(reports_dir):
            report_path = os.path.join(reports_dir, report_folder)
            if not os.path.isdir(report_path):
                continue

            meta_file = os.path.join(report_path, "meta.json")
            if not os.path.exists(meta_file):
                continue

            try:
                with open(meta_file, encoding="utf-8") as f:
                    meta = json.load(f)

                if meta.get("simulation_id") == simulation_id:
                    matching_reports.append(
                        {
                            "report_id": meta.get("report_id"),
                            "created_at": meta.get("created_at", ""),
                            "status": meta.get("status", ""),
                        }
                    )
            except Exception:
                continue

        if not matching_reports:
            return None

        matching_reports.sort(key=lambda x: x.get("created_at", ""), reverse=True)
        return matching_reports[0].get("report_id")

    except Exception as e:
        logger.warning(f"Failed to find report for simulation {simulation_id}: {e}")
        return None


@simulation_bp.route("/history", methods=["GET"])
@require_auth
def get_simulation_history():
    """
    Get historical simulation list (with project details)

    Used for homepage historical project display, returns simulation list
    enriched with project name, description, etc.

    Query parameters:
        limit: Result count limit (default 20)

    Returns:
        {
            "success": true,
            "data": [
                {
                    "simulation_id": "sim_xxxx",
                    "project_id": "proj_xxxx",
                    "project_name": "Sentiment Analysis",
                    "simulation_requirement": "If the university publishes...",
                    "status": "completed",
                    "entities_count": 68,
                    "profiles_count": 68,
                    "entity_types": ["Student", "Professor", ...],
                    "created_at": "2024-12-10",
                    "updated_at": "2024-12-10",
                    "total_rounds": 120,
                    "current_round": 120,
                    "report_id": "report_xxxx",
                    "version": "v1.0.2"
                },
                ...
            ],
            "count": 7
        }
    """
    try:
        limit = request.args.get("limit", 20, type=int)

        # Simulations explicitly recorded for this user in Supabase
        user_sim_ids = set()
        user_sims = SupabaseDB.list_simulations(g.user_id, limit=max(limit, 100))
        for s in user_sims:
            user_sim_ids.add(s.get("id"))

        # Projects owned by this user — include local disk sims under those projects
        # even if the simulations row was never inserted (common after migrations / edge cases)
        user_project_ids = set()
        for p in SupabaseDB.list_projects(g.user_id, limit=200):
            pid = p.get("id")
            if pid:
                user_project_ids.add(pid)

        manager = SimulationManager()
        all_sims = manager.list_simulations()

        def _user_owns_simulation(state) -> bool:
            if state.simulation_id in user_sim_ids:
                return True
            if state.project_id and state.project_id in user_project_ids:
                return True
            return False

        simulations = [s for s in all_sims if _user_owns_simulation(s)]
        # Newest first (folder iteration order is not reliable)
        simulations.sort(key=lambda s: s.created_at or "", reverse=True)
        simulations = simulations[:limit]

        enriched_simulations = []
        for sim in simulations:
            sim_dict = sim.to_dict()

            config = manager.get_simulation_config(sim.simulation_id)
            if config:
                sim_dict["simulation_requirement"] = config.get("simulation_requirement", "")
                time_config = config.get("time_config", {})
                sim_dict["total_simulation_hours"] = time_config.get("total_simulation_hours", 0)
                sim_dict["time_scale"] = time_config.get("time_scale", {"unit": "hour", "per_round": 1})
                sim_dict["phases"] = time_config.get("phases", [])

                time_scale = time_config.get("time_scale", {})
                if time_scale.get("unit", "hour") != "hour":
                    recommended_rounds = time_scale.get("total_duration", 60) // max(time_scale.get("per_round", 1), 1)
                else:
                    recommended_rounds = int(
                        time_config.get("total_simulation_hours", 0)
                        * 60
                        / max(time_config.get("minutes_per_round", 60), 1)
                    )
            else:
                sim_dict["simulation_requirement"] = ""
                sim_dict["total_simulation_hours"] = 0
                sim_dict["time_scale"] = {"unit": "hour", "per_round": 1}
                sim_dict["phases"] = []
                recommended_rounds = 0

            run_state = SimulationRunner.get_run_state(sim.simulation_id)
            if run_state:
                sim_dict["current_round"] = run_state.current_round
                sim_dict["runner_status"] = run_state.runner_status.value
                sim_dict["total_rounds"] = run_state.total_rounds if run_state.total_rounds > 0 else recommended_rounds
            else:
                sim_dict["current_round"] = 0
                sim_dict["runner_status"] = "idle"
                sim_dict["total_rounds"] = recommended_rounds

            project = ProjectManager.get_project(sim.project_id)
            if project and hasattr(project, "files") and project.files:
                sim_dict["files"] = [{"filename": f.get("filename", "Unknown file")} for f in project.files[:3]]
            else:
                sim_dict["files"] = []

            if project and hasattr(project, "decision_intake"):
                sim_dict["decision_intake"] = project.decision_intake

            report_id = _get_report_id_for_simulation(sim.simulation_id)
            sim_dict["report_id"] = report_id

            if report_id:
                try:
                    payload = ReportManager.load_payload_v1(report_id)
                    if payload:
                        decision = payload.get("decision", {}) or {}
                        sim_dict["report_summary"] = {
                            "verdict": decision.get("verdict"),
                            "confidence": decision.get("confidence"),
                        }
                        mc = payload.get("monte_carlo", {}) or {}
                        mc_composite = mc.get("composite", {}) or {}
                        if mc_composite:
                            ci95 = (mc_composite.get("confidence_intervals", {}) or {}).get("95%")
                            sim_dict["report_summary"]["mc_mean"] = mc_composite.get("mean")
                            sim_dict["report_summary"]["mc_ci_95"] = ci95
                except Exception:
                    pass

            sim_dict["version"] = "v1.0.2"

            sim_dict["created_date"] = (sim_dict.get("created_at") or "")[:10]

            enriched_simulations.append(sim_dict)

        return jsonify({"success": True, "data": enriched_simulations, "count": len(enriched_simulations)})

    except Exception as e:
        logger.error(f"Failed to get simulation history: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


@simulation_bp.route("/<simulation_id>/profiles", methods=["GET"])
@require_auth
def get_simulation_profiles(simulation_id: str):
    """
    Get simulation Agent profiles

    Query parameters:
        platform: Platform type (reddit/twitter, default reddit)
    """
    try:
        platform = request.args.get("platform", "reddit")

        manager = SimulationManager()
        profiles = manager.get_profiles(simulation_id, platform=platform)

        return jsonify({"success": True, "data": {"platform": platform, "count": len(profiles), "profiles": profiles}})

    except ValueError as e:
        return jsonify({"success": False, "error": str(e)}), 404

    except Exception as e:
        logger.error(f"Failed to get profiles: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


@simulation_bp.route("/<simulation_id>/profiles/realtime", methods=["GET"])
@require_auth
def get_simulation_profiles_realtime(simulation_id: str):
    """
    Real-time retrieval of simulation Agent profiles (for viewing progress during generation)

    Differs from /profiles:
    - Reads files directly, bypassing SimulationManager
    - Suitable for real-time viewing during generation
    - Returns additional metadata (file modification time, generation status, etc.)

    Query parameters:
        platform: Platform type (reddit/twitter, default reddit)

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "platform": "reddit",
                "count": 15,
                "total_expected": 93,
                "is_generating": true,
                "file_exists": true,
                "file_modified_at": "2025-12-04T18:20:00",
                "profiles": [...]
            }
        }
    """
    import csv
    from datetime import datetime

    try:
        platform = request.args.get("platform", "reddit")

        sim_dir = os.path.join(Config.OASIS_SIMULATION_DATA_DIR, simulation_id)

        if not os.path.exists(sim_dir):
            return jsonify({"success": False, "error": f"Simulation not found: {simulation_id}"}), 404

        if platform == "reddit":
            profiles_file = os.path.join(sim_dir, "reddit_profiles.json")
        else:
            profiles_file = os.path.join(sim_dir, "twitter_profiles.csv")

        file_exists = os.path.exists(profiles_file)
        profiles = []
        file_modified_at = None

        if file_exists:
            file_stat = os.stat(profiles_file)
            file_modified_at = datetime.fromtimestamp(file_stat.st_mtime).isoformat()

            try:
                if platform == "reddit":
                    with open(profiles_file, encoding="utf-8") as f:
                        profiles = json.load(f)
                else:
                    with open(profiles_file, encoding="utf-8") as f:
                        reader = csv.DictReader(f)
                        profiles = list(reader)
            except (json.JSONDecodeError, Exception) as e:
                logger.warning(f"Failed to read profiles file (may be in progress): {e}")
                profiles = []

        is_generating = False
        total_expected = None

        state_file = os.path.join(sim_dir, "state.json")
        if os.path.exists(state_file):
            try:
                with open(state_file, encoding="utf-8") as f:
                    state_data = json.load(f)
                    status = state_data.get("status", "")
                    is_generating = status == "preparing"
                    total_expected = state_data.get("entities_count")
            except Exception:
                pass

        return jsonify(
            {
                "success": True,
                "data": {
                    "simulation_id": simulation_id,
                    "platform": platform,
                    "count": len(profiles),
                    "total_expected": total_expected,
                    "is_generating": is_generating,
                    "file_exists": file_exists,
                    "file_modified_at": file_modified_at,
                    "profiles": profiles,
                },
            }
        )

    except Exception as e:
        logger.error(f"Failed to get profiles in real-time: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


@simulation_bp.route("/<simulation_id>/config/realtime", methods=["GET"])
@require_auth
def get_simulation_config_realtime(simulation_id: str):
    """
    Real-time retrieval of simulation config (for viewing progress during generation)

    Differs from /config:
    - Reads files directly, bypassing SimulationManager
    - Suitable for real-time viewing during generation
    - Returns additional metadata (file modification time, generation status, etc.)
    - Can return partial info even if config is not yet fully generated

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "file_exists": true,
                "file_modified_at": "2025-12-04T18:20:00",
                "is_generating": true,
                "generation_stage": "generating_config",
                "config": {...}
            }
        }
    """
    from datetime import datetime

    try:
        sim_dir = os.path.join(Config.OASIS_SIMULATION_DATA_DIR, simulation_id)

        if not os.path.exists(sim_dir):
            return jsonify({"success": False, "error": f"Simulation not found: {simulation_id}"}), 404

        config_file = os.path.join(sim_dir, "simulation_config.json")

        file_exists = os.path.exists(config_file)
        config = None
        file_modified_at = None

        if file_exists:
            file_stat = os.stat(config_file)
            file_modified_at = datetime.fromtimestamp(file_stat.st_mtime).isoformat()

            try:
                with open(config_file, encoding="utf-8") as f:
                    config = json.load(f)
            except (json.JSONDecodeError, Exception) as e:
                logger.warning(f"Failed to read config file (may be in progress): {e}")
                config = None

        is_generating = False
        generation_stage = None
        config_generated = False

        state_file = os.path.join(sim_dir, "state.json")
        if os.path.exists(state_file):
            try:
                with open(state_file, encoding="utf-8") as f:
                    state_data = json.load(f)
                    status = state_data.get("status", "")
                    is_generating = status == "preparing"
                    config_generated = state_data.get("config_generated", False)

                    if is_generating:
                        if state_data.get("profiles_generated", False):
                            generation_stage = "generating_config"
                        else:
                            generation_stage = "generating_profiles"
                    elif status == "ready":
                        generation_stage = "completed"
            except Exception:
                pass

        warnings = []
        if os.path.exists(state_file):
            try:
                with open(state_file, encoding="utf-8") as f:
                    warnings = json.load(f).get("warnings", [])
            except Exception:
                pass

        response_data = {
            "simulation_id": simulation_id,
            "file_exists": file_exists,
            "file_modified_at": file_modified_at,
            "is_generating": is_generating,
            "generation_stage": generation_stage,
            "config_generated": config_generated,
            "config": config,
            "warnings": warnings,
        }

        if config:
            response_data["summary"] = {
                "total_agents": len(config.get("agent_configs", [])),
                "simulation_hours": config.get("time_config", {}).get("total_simulation_hours"),
                "initial_posts_count": len(config.get("event_config", {}).get("initial_posts", [])),
                "hot_topics_count": len(config.get("event_config", {}).get("hot_topics", [])),
                "has_twitter_config": "twitter_config" in config,
                "has_reddit_config": "reddit_config" in config,
                "generated_at": config.get("generated_at"),
                "llm_model": config.get("llm_model"),
            }

        return jsonify({"success": True, "data": response_data})

    except Exception as e:
        logger.error(f"Failed to get config in real-time: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


@simulation_bp.route("/<simulation_id>/config", methods=["GET"])
@require_auth
def get_simulation_config(simulation_id: str):
    """
    Get simulation config (LLM-generated complete config)

    Returns:
        - time_config: Time configuration (simulation duration, rounds, peak/off-peak periods)
        - agent_configs: Per-agent activity config (activity level, posting frequency, stance, etc.)
        - event_config: Event configuration (initial posts, hot topics)
        - platform_configs: Platform configuration
        - generation_reasoning: LLM's config reasoning explanation
    """
    try:
        manager = SimulationManager()
        config = manager.get_simulation_config(simulation_id)

        if not config:
            return jsonify(
                {"success": False, "error": "Simulation config not found, please call /prepare endpoint first"}
            ), 404

        return jsonify({"success": True, "data": config})

    except Exception as e:
        logger.error(f"Failed to get config: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


@simulation_bp.route("/<simulation_id>/config/download", methods=["GET"])
@require_auth
def download_simulation_config(simulation_id: str):
    """Download simulation config file"""
    try:
        manager = SimulationManager()
        sim_dir = manager._get_simulation_dir(simulation_id)
        config_path = os.path.join(sim_dir, "simulation_config.json")

        if not os.path.exists(config_path):
            return jsonify(
                {"success": False, "error": "Config file not found, please call /prepare endpoint first"}
            ), 404

        return send_file(config_path, as_attachment=True, download_name="simulation_config.json")

    except Exception as e:
        logger.error(f"Failed to download config: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


@simulation_bp.route("/script/<script_name>/download", methods=["GET"])
@require_auth
def download_simulation_script(script_name: str):
    """
    Download simulation run script (shared scripts located in backend/scripts/)

    script_name options:
        - run_twitter_simulation.py
        - run_reddit_simulation.py
        - run_parallel_simulation.py
        - action_logger.py
    """
    try:
        scripts_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../scripts"))

        allowed_scripts = [
            "run_twitter_simulation.py",
            "run_reddit_simulation.py",
            "run_parallel_simulation.py",
            "action_logger.py",
        ]

        if script_name not in allowed_scripts:
            return jsonify(
                {"success": False, "error": f"Unknown script: {script_name}, options: {allowed_scripts}"}
            ), 400

        script_path = os.path.join(scripts_dir, script_name)

        if not os.path.exists(script_path):
            return jsonify({"success": False, "error": f"Script file not found: {script_name}"}), 404

        return send_file(script_path, as_attachment=True, download_name=script_name)

    except Exception as e:
        logger.error(f"Failed to download script: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


# ============== Profile Generation Endpoint (standalone) ==============


@simulation_bp.route("/generate-profiles", methods=["POST"])
@require_auth
def generate_profiles():
    """
    Generate OASIS Agent profiles directly from graph (without creating a simulation)

    Request (JSON):
        {
            "graph_id": "glas_xxxx",     // required
            "entity_types": ["Student"],      // optional
            "use_llm": true,                  // optional
            "platform": "reddit"              // optional
        }
    """
    try:
        data = request.get_json() or {}

        graph_id = data.get("graph_id")
        if not graph_id:
            return jsonify({"success": False, "error": "Please provide graph_id"}), 400

        entity_types = data.get("entity_types")
        use_llm = data.get("use_llm", True)
        platform = data.get("platform", "reddit")

        reader = ZepEntityReader()
        filtered = reader.filter_defined_entities(
            graph_id=graph_id, defined_entity_types=entity_types, enrich_with_edges=True
        )

        if filtered.filtered_count == 0:
            return jsonify({"success": False, "error": "No matching entities found"}), 400

        generator = OasisProfileGenerator()
        profiles = generator.generate_profiles_from_entities(entities=filtered.entities, use_llm=use_llm)

        if platform == "reddit":
            profiles_data = [p.to_reddit_format() for p in profiles]
        elif platform == "twitter":
            profiles_data = [p.to_twitter_format() for p in profiles]
        else:
            profiles_data = [p.to_dict() for p in profiles]

        return jsonify(
            {
                "success": True,
                "data": {
                    "platform": platform,
                    "entity_types": list(filtered.entity_types),
                    "count": len(profiles_data),
                    "profiles": profiles_data,
                },
            }
        )

    except Exception as e:
        logger.error(f"Failed to generate profiles: {str(e)}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


from . import simulation_run_routes  # noqa: F401
from . import simulation_interview_env_routes  # noqa: F401
